export const enum MODAL_ACTION_TYPE {
  OPEN_MODAL,
  CLOSE_MODAL,
  OPEN_AUTHENTICATION_MODAL,
  CLOSE_AUTHENTICATION_MODAL,
  OPEN_SETTINGS_MODAL,
  CLOSE_SETTINGS_MODAL,
  OPEN_PROMPT_MODAL,
  CLOSE_PROMPT_MODAL,
}
