import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import GlobalContext from "../services/context/GlobalContext";
import ChatSidebar from "@/components/sidebar/chatSidebar/ChatSidebar";
import PromptSideBar from "@/components/sidebar/promptSidebar/PromptSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalContext>
          <main className="flex h-screen w-screen flex-col text-sm text-white dark:text-white dark">
            <div id="modal-root"></div>
            <div className="flex h-full w-full pt-[48px] sm:pt-0">
              <ChatSidebar />
              {children}
              <PromptSideBar />
            </div>
          </main>
        </GlobalContext>
      </body>
    </html>
  );
}
